import { Employee } from './employes';
export const employes: Employee[] = [
  {
    id: 1,
    Nom: 'Dion',
    prenom: 'Céline',
    position: 'Formatrice en Informatique',
    date: '30 mars 2007',
    rubrique: [],
  },
  {
    id: 2,
    Nom: 'Seydoux',
    prenom: 'Léa',
    position: 'Testeuse',
    date: '30 septembre 2014',
    rubrique: [],
  },
  {
    id: 3,
    Nom: 'Monet',
    prenom: 'Claude',
    position: 'Chef de Projet Informatique',
    date: '14 novembre 2012',
    rubrique: [],
  },
  {
    id: 4,
    Nom: 'Cotillard',
    prenom: 'Marion',
    position: 'Développeur Web',
    date: '30 septembre 2011Léo',
    rubrique: [],
  },
  {
    id: 5,
    Nom: 'Dupont',
    prenom: 'Léo',
    position: 'Ingénieur technio-commercial en Informatique',
    date: '28 mars 2012',
    rubrique: [],
  },
  {
    id: 6,
    Nom: 'Drucaire',
    prenom: 'Danielle',
    position: 'Technicienne en maintenance en Informatique',
    date: '2 août 2016',
    rubrique: [],
  },
  {
    id: 7,
    Nom: 'Bourjois',
    prenom: 'Jack',
    position: 'Ingénieur système',
    date: '22 septembre 2017',
    rubrique: [],
  },
  {
    id: 8,
    Nom: 'Durant',
    prenom: 'Thomas',
    position: 'Consultant en système information',
    date: '13 octobre 2009',
    rubrique: [],
  },
  {
    id: 9,
    Nom: 'Morel',
    prenom: 'Jasmine',
    position: 'Administratrice de réseau',
    date: '30 mars 2005',
    rubrique: [],
  },
  {
    id: 10,
    Nom: 'Hubert',
    prenom: 'Louis',
    position: 'Ingénieur Cloud Computing',
    date: '7 juillet 2004',
    rubrique: [],
  },
  {
    id: 11,
    Nom: 'Simon',
    prenom: 'Fabienne',
    position: 'Ingénieure développement en Logiciel de simulation',
    date: '18 novembre 2011',
    rubrique: [],
  },
  {
    id: 12,
    Nom: 'Mercier',
    prenom: 'Charlotte',
    position: 'Technicienne télécom et réseaux Informatique',
    date: '27 août 2007',
    rubrique: [],
  },
];
